'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import { ArrowLeft,Mail,RefreshCw,CalendarDays,Users,MessageSquare,TrendingUp,Wallet,AlertTriangle } from 'lucide-react'
type Period='weekly'|'monthly'
const fmt=(n:number)=>new Intl.NumberFormat('en-US').format(n||0)
const money=(n:number)=>'UGX '+fmt(n)
function Card({label,value,sub}:{label:string,value:string|number,sub?:string}){return <div className="rounded-2xl border border-gray-100 dark:border-white/10 bg-white dark:bg-white/5 p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-gray-400">{label}</p><p className="mt-2 text-3xl font-black text-clinic-navy dark:text-white">{value}</p>{sub&&<p className="mt-1 text-xs text-gray-400">{sub}</p>}</div>}
function Section({title,icon:Icon,children}:{title:string,icon:any,children:any}){return <section className="rounded-2xl border border-gray-100 dark:border-white/10 bg-white dark:bg-white/5 overflow-hidden"><div className="flex items-center gap-2 border-b border-gray-100 dark:border-white/10 px-5 py-4"><Icon size={17} className="text-cyan-500"/><h2 className="font-black text-gray-800 dark:text-white">{title}</h2></div><div className="p-5">{children}</div></section>}
function Rows({rows}:{rows:[string,any][]}){return <div className="grid sm:grid-cols-2 gap-x-8">{rows.map(([k,v])=><div key={k} className="flex justify-between gap-4 py-2.5 border-b border-gray-50 dark:border-white/5 text-sm"><span className="text-gray-500 dark:text-white/50">{k}</span><strong className="text-gray-800 dark:text-white text-right">{v}</strong></div>)}</div>}
export default function ExecutiveReportPage(){
 const [period,setPeriod]=useState<Period>('weekly'),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[sending,setSending]=useState(false),[msg,setMsg]=useState('')
 const token=typeof window!=='undefined'?localStorage.getItem('cc_token'):null
 async function load(p=period){setLoading(true);setMsg('');try{const r=await fetch(`/api-proxy/reports/executive?period=${p}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not generate report');setData(await r.json())}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load(period)},[period])
 async function sendTest(){if(!email)return;setSending(true);setMsg('');try{const r=await fetch('/api-proxy/reports/executive/test-email',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({period,to:email})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Test email failed');setMsg(`Test report sent to ${b.to}`)}catch(e:any){setMsg(e.message)}finally{setSending(false)}}
 const c=data?.current,cmp=data?.comparisons
 return <div className="p-6 space-y-6 max-w-6xl">
  <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><Link href="/reports" className="p-2 rounded-xl hover:bg-gray-100 dark:hover:bg-white/10 text-gray-400"><ArrowLeft size={17}/></Link><div><h1 className="text-xl font-black text-clinic-navy dark:text-white">Admin Executive Report</h1><p className="text-sm text-gray-400">Appointments, patient flow, CRM, communications, treatment pipeline and collections</p></div></div>
  <div className="flex gap-2">{(['weekly','monthly'] as Period[]).map(p=><button key={p} onClick={()=>setPeriod(p)} className={`px-4 py-2 rounded-xl text-sm font-bold capitalize border ${period===p?'bg-clinic-navy text-white border-clinic-navy':'bg-white dark:bg-white/5 border-gray-200 dark:border-white/10 text-gray-500'}`}>{p}</button>)}<button onClick={()=>load()} className="p-2.5 rounded-xl border border-gray-200 dark:border-white/10 text-gray-500"><RefreshCw size={16} className={loading?'animate-spin':''}/></button></div></div>
  {msg&&<div className="rounded-xl bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 px-4 py-3 text-sm">{msg}</div>}
  {loading?<div className="py-24 text-center text-gray-400">Generating report from live clinic records…</div>:data&&<>
   <div className="rounded-3xl p-7 text-white" style={{background:'linear-gradient(135deg,#0c1e50,#1A237E 55%,#29ABE2)'}}><p className="text-xs uppercase tracking-[.2em] text-cyan-200 font-bold">Code Clinic · {data.period.kind} management brief</p><h2 className="text-3xl font-black mt-2">{data.period.label}</h2><p className="mt-2 text-sm text-blue-100">Compared with {data.period.previousLabel} · Generated {new Date(data.generatedAt).toLocaleString()}</p></div>
   <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4"><Card label="Appointments" value={c.appointments.scheduled} sub={cmp.scheduledAppointmentsPct==null?'No prior baseline':`${cmp.scheduledAppointmentsPct>=0?'+':''}${cmp.scheduledAppointmentsPct}% vs prior`}/><Card label="Patients seen" value={c.appointments.patientsSeen}/><Card label="New CRM leads" value={c.crm.newLeads} sub={`${c.crm.converted} converted`}/><Card label="Conversations" value={c.communications.conversations}/><Card label="Collected" value={money(c.finance.collectedUGX)}/></div>
   {data.attention.length>0&&<div className="rounded-2xl border border-amber-200 bg-amber-50 dark:bg-amber-900/10 dark:border-amber-800/40 p-5"><div className="flex items-center gap-2 font-black text-amber-800 dark:text-amber-300"><AlertTriangle size={17}/>Management attention</div><ul className="mt-3 space-y-2 text-sm text-amber-800/80 dark:text-amber-200/70 list-disc pl-5">{data.attention.map((x:string)=><li key={x}>{x}</li>)}</ul></div>}
   <div className="grid lg:grid-cols-2 gap-5">
    <Section title="Appointments & Patient Flow" icon={CalendarDays}><Rows rows={[['Scheduled',c.appointments.scheduled],['Patients seen',c.appointments.patientsSeen],['Attended appointments',c.appointments.attended],['Confirmed',c.appointments.confirmed],['Pending',c.appointments.pending],['Cancelled',c.appointments.cancelled],['No-shows',c.appointments.noShows],['Rescheduled',c.appointments.rescheduled],['Avg. arrival → provider',c.appointments.avgWaitMinutes==null?'No measured data':c.appointments.avgWaitMinutes+' min']]}/></Section>
    <Section title="CRM Leads" icon={Users}><Rows rows={[['New leads',c.crm.newLeads],['Converted',c.crm.converted],['Conversion rate',c.crm.conversionRate+'%'],['Avg. first human reply',c.crm.avgFirstHumanReplyMinutes==null?'No measured data':c.crm.avgFirstHumanReplyMinutes+' min'],...Object.entries(c.crm.bySource).map(([k,v])=>['Source · '+k,v] as [string,any])]}/></Section>
    <Section title="Communications" icon={MessageSquare}><Rows rows={[['New conversations',c.communications.conversations],['Inbound messages',c.communications.inboundMessages],['Sarah/agent messages',c.communications.agentMessages],['Human takeovers',c.communications.humanTakeovers],['Failed deliveries',c.communications.failedAgentMessages],...Object.entries(c.communications.byChannel).map(([k,v])=>['Channel · '+k,v] as [string,any])]}/></Section>
    <Section title="Treatment Pipeline" icon={TrendingUp}><Rows rows={[['Plans presented',c.treatment.plansPresented],['Accepted',c.treatment.accepted],['Pending / on hold',c.treatment.pending],['Declined',c.treatment.declined],['Acceptance rate',c.treatment.acceptanceRate+'%'],['Money at risk',money(c.treatment.moneyAtRiskUGX)]]}/></Section>
   </div>
   <Section title="Collections" icon={Wallet}><Rows rows={[['Actual recorded collections',money(c.finance.collectedUGX)],['Change vs prior period',cmp.collectedRevenuePct==null?'No prior baseline':`${cmp.collectedRevenuePct>=0?'+':''}${cmp.collectedRevenuePct}%`]]}/><p className="mt-3 text-xs text-gray-400">This is recorded Payment collection data, not assumed CRM-attributed revenue.</p></Section>
   <Section title="Test Email Delivery" icon={Mail}><p className="text-sm text-gray-500 dark:text-white/50 mb-4">Nothing is scheduled yet. Enter a recipient to send this exact report as a professional test email.</p><div className="flex flex-col sm:flex-row gap-3"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com" className="flex-1 rounded-xl border border-gray-200 dark:border-white/10 bg-white dark:bg-gray-900 px-4 py-2.5 text-sm"/><button disabled={!email||sending} onClick={sendTest} className="rounded-xl bg-cyan-500 disabled:opacity-50 text-white font-bold px-5 py-2.5">{sending?'Sending…':'Send Test Email'}</button></div></Section>
  </>}
 </div>
}
